name: build
on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: eskatos/gradle-command-action@v3
        with:
          arguments: :build
      - uses: eskatos/gradle-command-action@v3
        with:
          arguments: build -x :build